### ISSUE TITLE
Can't create a lobby to play

### ISSUE THREAD

**Issue by Mxnority** [Hardel-DW/TooManyRolesMods#1]
![image](https://user-images.githubusercontent.com/45408633/108932812-fdd74100-7617-11eb-8b85-7fb727b84e90.png)

**Comment by Hardel-DW** [comment]
Hello,
It's fixed in the version 1.2.

**Comment by Mxnority** [comment]
Hi, is version 1.2 available? I don't see it...

**Comment by Mxnority** [comment]
Nevermind, i see it now, thank you!

**Comment by Hardel-DW** [comment]
The error is always present, I am trying to find a way to solve this problem.

**Comment by Hardel-DW** [comment]
The version 1.2.1 fix it.
I just tried it on NA server.

![Among_Us_Lc05o5mZbp](https://user-images.githubusercontent.com/42413417/108940089-0dc04680-7653-11eb-9791-6fe42bd0fe43.png)

**Comment by Mxnority** [comment]
Wow, you're very poggers, do you have a discord server?

**Comment by Hardel-DW** [comment]
Yes, i have :
https://discord.gg/AP9axbXXNC

I created them 2 days ago.
I plan to make it grow very quickly.

**Comment by Mxnority** [comment]
Nice, i joined, hope that works out for you
